/* 업그레이드 된 아이템 구하기 (Find upgraded items) */
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_INFO A, ITEM_TREE B
 WHERE B.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY='RARE')
   AND A.ITEM_ID = B.ITEM_ID 
ORDER BY A.ITEM_ID DESC