/* 서울에 위치한 식당 목록 출력 (List of restaurants located in Seoul) */
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE 
  FROM REST_INFO I, REST_REVIEW R
 WHERE I.ADDRESS LIKE '서울%'
   AND I.REST_ID IN (SELECT REST_ID FROM REST_REVIEW)
 GROUP BY I.REST_ID
 ORDER BY SCORE DESC, I.FAVORITES DESC