/* 3월에 태어난 여성 회원 목록 출력 (List of female members born in March) */
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD')
  FROM MEMBER_PROFILE
 WHERE GENDER = 'W'
   AND TRIM(TLNO) IS NOT NULL
   AND TO_CHAR(DATE_OF_BIRTH, 'YYYYMM') LIKE '%03'
 ORDER BY MEMBER_ID