/* 오프라인/온라인 판매 데이터 통합 (Intergration of sales from offline and online) */
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD'), PRODUCT_ID, USER_ID, SALES_AMOUNT
  FROM (SELECT ONLINE_SALE_ID AS SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
        UNION ALL
        SELECT OFFLINE_SALE_ID AS SALE_ID, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE)
 WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
 ORDER BY SALES_DATE, PRODUCT_ID, USER_ID